"""schema inicial

Revision ID: 7337dbec3b13
Revises:
Create Date: 2026-07-14 20:36:13.683628

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "7337dbec3b13"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Necessária para a EXCLUDE constraint anti-sobreposição de rentals
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("cpf", sa.String(length=11), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("cnh_number", sa.String(length=11), nullable=True),
        sa.Column("cnh_category", sa.String(length=5), nullable=True),
        sa.Column("cnh_expires_at", sa.Date(), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("address_cep", sa.String(length=8), nullable=True),
        sa.Column("address_street", sa.String(length=150), nullable=True),
        sa.Column("address_number", sa.String(length=20), nullable=True),
        sa.Column("address_complement", sa.String(length=100), nullable=True),
        sa.Column("address_district", sa.String(length=100), nullable=True),
        sa.Column("address_city", sa.String(length=100), nullable=True),
        sa.Column("address_state", sa.String(length=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(cpf) = 11", name=op.f("ck_clients_cpf_11_digitos")),
        sa.CheckConstraint(
            "cnh_number IS NULL OR char_length(cnh_number) = 11",
            name=op.f("ck_clients_cnh_11_digitos"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
        sa.UniqueConstraint("cpf", name=op.f("uq_clients_cpf")),
    )
    op.create_index("ix_clients_full_name", "clients", ["full_name"], unique=False)
    op.create_table(
        "trailers",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("plate", sa.String(length=10), nullable=True),
        sa.Column("renavam", sa.String(length=11), nullable=True),
        sa.Column("length_m", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("width_m", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("height_m", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("load_capacity_kg", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("daily_rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("hourly_rate", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("deposit_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE",
                "RESERVED",
                "RENTED",
                "MAINTENANCE",
                "INACTIVE",
                name="trailer_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="AVAILABLE",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("daily_rate > 0", name=op.f("ck_trailers_daily_rate_positiva")),
        sa.CheckConstraint(
            "deposit_amount IS NULL OR deposit_amount >= 0",
            name=op.f("ck_trailers_deposit_nao_negativo"),
        ),
        sa.CheckConstraint(
            "hourly_rate IS NULL OR hourly_rate > 0", name=op.f("ck_trailers_hourly_rate_positiva")
        ),
        sa.CheckConstraint(
            "length_m > 0 AND width_m > 0 AND height_m > 0",
            name=op.f("ck_trailers_dimensoes_positivas"),
        ),
        sa.CheckConstraint("load_capacity_kg > 0", name=op.f("ck_trailers_capacidade_positiva")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trailers")),
        sa.UniqueConstraint("code", name=op.f("uq_trailers_code")),
        sa.UniqueConstraint("plate", name=op.f("uq_trailers_plate")),
    )
    op.create_index(
        "ix_trailers_status_is_active", "trailers", ["status", "is_active"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN",
                "GESTOR",
                "ATENDENTE",
                "VISTORIADOR",
                "VIEWER",
                name="user_role",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "must_change_password", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=60), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("result", sa.String(length=20), nullable=False),
        sa.Column("ip_prefix", sa.String(length=45), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_actor_created", "audit_logs", ["actor_user_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_logs_entity",
        "audit_logs",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "maintenance_orders",
        sa.Column("trailer_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                name="maintenance_priority",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            server_default="MEDIUM",
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected_end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("final_cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="maintenance_status",
                native_enum=False,
                create_constraint=True,
                length=15,
            ),
            server_default="OPEN",
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_to_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estimated_cost IS NULL OR estimated_cost >= 0",
            name=op.f("ck_maintenance_orders_custo_estimado_nao_negativo"),
        ),
        sa.CheckConstraint(
            "expected_end_at IS NULL OR expected_end_at > starts_at",
            name=op.f("ck_maintenance_orders_fim_apos_inicio"),
        ),
        sa.CheckConstraint(
            "final_cost IS NULL OR final_cost >= 0",
            name=op.f("ck_maintenance_orders_custo_final_nao_negativo"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_user_id"],
            ["users.id"],
            name=op.f("fk_maintenance_orders_assigned_to_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_maintenance_orders_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trailer_id"],
            ["trailers.id"],
            name=op.f("fk_maintenance_orders_trailer_id_trailers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_orders")),
    )
    op.create_index(
        "ix_maintenance_trailer_agenda",
        "maintenance_orders",
        ["trailer_id", "starts_at", "expected_end_at", "status"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip_prefix", sa.String(length=45), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "rentals",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("trailer_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("pickup_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("return_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected_return_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actual_return_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "period_type",
            sa.Enum(
                "DAYS",
                "HOURS",
                name="period_type",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("period_quantity", sa.Integer(), nullable=False),
        sa.Column("daily_rate_snapshot", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("hourly_rate_snapshot", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("deposit_amount_snapshot", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=10, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("total_expected", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_final", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "RESERVED",
                "ACTIVE",
                "OVERDUE",
                "COMPLETED",
                "CANCELLED",
                name="rental_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("discount_amount >= 0", name=op.f("ck_rentals_desconto_nao_negativo")),
        sa.CheckConstraint(
            "expected_return_at > start_at", name=op.f("ck_rentals_devolucao_apos_retirada")
        ),
        sa.CheckConstraint("period_quantity >= 1", name=op.f("ck_rentals_period_quantity_minimo")),
        sa.CheckConstraint(
            "total_expected >= 0", name=op.f("ck_rentals_total_previsto_nao_negativo")
        ),
        sa.CheckConstraint(
            "total_final IS NULL OR total_final >= 0",
            name=op.f("ck_rentals_total_final_nao_negativo"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_rentals_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_rentals_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pickup_by_user_id"],
            ["users.id"],
            name=op.f("fk_rentals_pickup_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["return_by_user_id"],
            ["users.id"],
            name=op.f("fk_rentals_return_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trailer_id"],
            ["trailers.id"],
            name=op.f("fk_rentals_trailer_id_trailers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rentals")),
        sa.UniqueConstraint("code", name=op.f("uq_rentals_code")),
    )
    op.create_index(
        "ix_rentals_client_created", "rentals", ["client_id", "created_at"], unique=False
    )
    op.create_index("ix_rentals_status", "rentals", ["status"], unique=False)
    op.create_index(
        "ix_rentals_trailer_agenda",
        "rentals",
        ["trailer_id", "start_at", "expected_return_at", "status"],
        unique=False,
    )
    op.create_table(
        "inspections",
        sa.Column("rental_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "PICKUP",
                "RETURN",
                name="inspection_type",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("structure_ok", sa.Boolean(), nullable=False),
        sa.Column("tires_ok", sa.Boolean(), nullable=False),
        sa.Column("lights_ok", sa.Boolean(), nullable=False),
        sa.Column("coupling_ok", sa.Boolean(), nullable=False),
        sa.Column("documents_ok", sa.Boolean(), nullable=False),
        sa.Column("is_clean", sa.Boolean(), nullable=False),
        sa.Column("mileage_km", sa.Numeric(precision=9, scale=1), nullable=True),
        sa.Column("observations", sa.Text(), nullable=True),
        sa.Column("responsible_name", sa.String(length=150), nullable=False),
        sa.Column("performed_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_user_id"],
            ["users.id"],
            name=op.f("fk_inspections_performed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rental_id"],
            ["rentals.id"],
            name=op.f("fk_inspections_rental_id_rentals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspections")),
        sa.UniqueConstraint("rental_id", "type", name="uq_inspections_rental_type"),
    )
    op.create_index(op.f("ix_inspections_rental_id"), "inspections", ["rental_id"], unique=False)
    op.create_table(
        "rental_history",
        sa.Column("rental_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("old_status", sa.String(length=20), nullable=True),
        sa.Column("new_status", sa.String(length=20), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rental_id"],
            ["rentals.id"],
            name=op.f("fk_rental_history_rental_id_rentals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_rental_history_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rental_history")),
    )
    op.create_index(
        "ix_rental_history_rental_created",
        "rental_history",
        ["rental_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "inspection_photos",
        sa.Column("inspection_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_inspection_photos_tamanho_positivo")),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["inspections.id"],
            name=op.f("fk_inspection_photos_inspection_id_inspections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inspection_photos")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_inspection_photos_storage_key")),
    )
    op.create_index(
        op.f("ix_inspection_photos_inspection_id"),
        "inspection_photos",
        ["inspection_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Garantia no banco: duas locações que ocupam agenda (RESERVED/ACTIVE/
    # OVERDUE) não podem se sobrepor para a mesma carreta, mesmo sob
    # concorrência. Complementa (não substitui) a checagem transacional
    # do serviço de reservas.
    op.execute(
        """
        ALTER TABLE rentals
        ADD CONSTRAINT ex_rentals_agenda_sem_sobreposicao
        EXCLUDE USING gist (
            trailer_id WITH =,
            tstzrange(start_at, expected_return_at) WITH &&
        )
        WHERE (status IN ('RESERVED', 'ACTIVE', 'OVERDUE'))
        """
    )


def downgrade() -> None:
    op.execute("ALTER TABLE rentals DROP CONSTRAINT IF EXISTS ex_rentals_agenda_sem_sobreposicao")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inspection_photos_inspection_id"), table_name="inspection_photos")
    op.drop_table("inspection_photos")
    op.drop_index("ix_rental_history_rental_created", table_name="rental_history")
    op.drop_table("rental_history")
    op.drop_index(op.f("ix_inspections_rental_id"), table_name="inspections")
    op.drop_table("inspections")
    op.drop_index("ix_rentals_trailer_agenda", table_name="rentals")
    op.drop_index("ix_rentals_status", table_name="rentals")
    op.drop_index("ix_rentals_client_created", table_name="rentals")
    op.drop_table("rentals")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_maintenance_trailer_agenda", table_name="maintenance_orders")
    op.drop_table("maintenance_orders")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_index("ix_trailers_status_is_active", table_name="trailers")
    op.drop_table("trailers")
    op.drop_index("ix_clients_full_name", table_name="clients")
    op.drop_table("clients")
    # ### end Alembic commands ###
