import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useAuth } from '@/auth/AuthContext'
import { listTrailers } from '@/api/trailers'
import { cancelMaintenance, completeMaintenance, createMaintenance, getOperationalAlerts, listMaintenance, startMaintenance, type MaintenancePayload, type MaintenancePriority } from '@/api/maintenance'

interface FormValues { trailer_id: string; type: string; description: string; priority: MaintenancePriority; starts_at: string; expected_end_at: string; estimated_cost: string }
const statusLabels: Record<string, string> = { OPEN: 'Aberta', IN_PROGRESS: 'Em andamento', COMPLETED: 'Concluída', CANCELLED: 'Cancelada' }
export default function Maintenance() {
  const { user } = useAuth(); const queryClient = useQueryClient(); const [open, setOpen] = useState(false)
  const canManage = ['ADMIN', 'GESTOR'].includes(user?.role ?? '')
  const form = useForm<FormValues>({ defaultValues: { priority: 'MEDIUM', starts_at: '', expected_end_at: '', estimated_cost: '' } })
  const orders = useQuery({ queryKey: ['maintenance'], queryFn: listMaintenance })
  const trailers = useQuery({ queryKey: ['trailers', '', true], queryFn: () => listTrailers('', true) })
  const alerts = useQuery({ queryKey: ['operational-alerts'], queryFn: getOperationalAlerts })
  const refresh = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['maintenance'] }), queryClient.invalidateQueries({ queryKey: ['trailers'] }), queryClient.invalidateQueries({ queryKey: ['agenda'] }), queryClient.invalidateQueries({ queryKey: ['operational-alerts'] })]) }
  const create = useMutation({ mutationFn: (values: FormValues) => { const payload: MaintenancePayload = { trailer_id: values.trailer_id, type: values.type, description: values.description, priority: values.priority, starts_at: new Date(values.starts_at).toISOString(), expected_end_at: values.expected_end_at ? new Date(values.expected_end_at).toISOString() : null, estimated_cost: values.estimated_cost ? Number(values.estimated_cost) : null }; return createMaintenance(payload) }, onSuccess: async () => { await refresh(); setOpen(false); form.reset() } })
  const action = useMutation({ mutationFn: async ({ id, type }: { id: string; type: 'start' | 'complete' | 'cancel' }) => { if (type === 'start') return startMaintenance(id); if (type === 'cancel') return cancelMaintenance(id); const value = window.prompt('Custo final da manutenção (R$):', '0'); if (value === null) throw new Error('Operação cancelada.'); return completeMaintenance(id, Number(value)) }, onSuccess: refresh })
  const trailerCode = (id: string) => trailers.data?.data.find((item) => item.id === id)?.code ?? id
  return <section className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Manutenções</h1><p className="text-slate-600">Ordens técnicas, custos e bloqueios da frota.</p></div>{canManage && <button className="btn-primary w-full sm:w-auto" onClick={() => setOpen(true)}>Nova ordem</button>}</div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="card"><p className="text-sm text-slate-500">Ordens abertas</p><p className="text-2xl font-bold">{alerts.data?.open_maintenance ?? '—'}</p></div><div className="card"><p className="text-sm text-slate-500">Alta prioridade</p><p className="text-2xl font-bold text-red-700">{alerts.data?.high_priority_maintenance ?? '—'}</p></div><div className="card"><p className="text-sm text-slate-500">Locações atrasadas</p><p className="text-2xl font-bold text-amber-700">{alerts.data?.overdue_rentals ?? '—'}</p></div><div className="card"><p className="text-sm text-slate-500">Retiradas em 24h</p><p className="text-2xl font-bold">{alerts.data?.returns_next_24h ?? '—'}</p></div></div>
    {open && <form className="card space-y-4" onSubmit={form.handleSubmit((values) => create.mutate(values))}><div className="flex justify-between"><h2 className="text-lg font-semibold">Nova ordem</h2><button type="button" className="btn-secondary" onClick={() => setOpen(false)}>Fechar</button></div><div className="grid gap-3 md:grid-cols-2"><label>Carreta<select className="input" {...form.register('trailer_id', { required: true })}><option value="">Selecione</option>{trailers.data?.data.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.id}>{item.code} · {item.model}</option>)}</select></label><label>Tipo<input className="input" {...form.register('type', { required: true })} /></label><label>Prioridade<select className="input" {...form.register('priority')}><option value="LOW">Baixa</option><option value="MEDIUM">Média</option><option value="HIGH">Alta</option></select></label><label>Custo estimado<input className="input" type="number" min="0" step="0.01" {...form.register('estimated_cost')} /></label><label>Início<input className="input" type="datetime-local" {...form.register('starts_at', { required: true })} /></label><label>Término previsto<input className="input" type="datetime-local" {...form.register('expected_end_at')} /></label></div><label>Descrição<textarea className="input min-h-24" {...form.register('description', { required: true })} /></label>{create.isError && <p className="text-red-700">{create.error instanceof Error ? create.error.message : 'Falha ao criar ordem.'}</p>}<button className="btn-primary">Criar ordem</button></form>}
    <div className="grid gap-3">{orders.data?.data.map((order) => <article className="card" key={order.id}><div className="flex flex-wrap justify-between gap-2"><div><p className="text-sm font-semibold text-primary">Carreta {trailerCode(order.trailer_id)}</p><h2 className="font-semibold">{order.type}</h2></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{statusLabels[order.status]} · {order.priority}</span></div><p className="mt-2 break-words text-sm text-slate-600">{order.description}</p><div className="mt-3 grid gap-1 text-sm sm:flex sm:flex-wrap sm:gap-3"><span>Início: {new Date(order.starts_at).toLocaleString('pt-BR')}</span><span>Estimado: R$ {order.estimated_cost ?? '—'}</span><span>Final: R$ {order.final_cost ?? '—'}</span></div>{canManage && ['OPEN', 'IN_PROGRESS'].includes(order.status) && <div className="mobile-actions mt-3 flex gap-2">{order.status === 'OPEN' && <button className="btn-primary" onClick={() => action.mutate({ id: order.id, type: 'start' })}>Iniciar</button>}<button className="btn-primary" onClick={() => action.mutate({ id: order.id, type: 'complete' })}>Concluir</button><button className="btn-secondary" onClick={() => action.mutate({ id: order.id, type: 'cancel' })}>Cancelar</button></div>}</article>)}</div></section>
}
