import { useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { useAuth } from '@/auth/AuthContext'
import { exportFinancial, exportOperations, getAuditReport, getFinancialReport, getOperations } from '@/api/reporting'

function dateValue(offsetDays = 0): string { const value = new Date(); value.setDate(value.getDate() + offsetDays); return value.toISOString().slice(0, 10) }
const statusLabels: Record<string, string> = { DRAFT: 'Rascunho', RESERVED: 'Reservada', ACTIVE: 'Ativa', OVERDUE: 'Atrasada', COMPLETED: 'Concluída', CANCELLED: 'Cancelada' }

export default function Reports() {
  const { user } = useAuth()
  const [start, setStart] = useState(dateValue(-30))
  const [end, setEnd] = useState(dateValue())
  const [status, setStatus] = useState('')
  const [filters, setFilters] = useState({ start, end, status })
  const canViewFinancial = ['ADMIN', 'GESTOR'].includes(user?.role ?? '')
  const operations = useQuery({ queryKey: ['reports', 'operations', filters], queryFn: () => getOperations(filters.start, filters.end, filters.status) })
  const financial = useQuery({ queryKey: ['reports', 'financial', filters.start, filters.end], queryFn: () => getFinancialReport(filters.start, filters.end), enabled: canViewFinancial })
  const audit = useQuery({ queryKey: ['reports', 'audit', filters.start, filters.end], queryFn: () => getAuditReport(filters.start, filters.end), enabled: canViewFinancial })
  const exportOps = useMutation({ mutationFn: () => exportOperations(filters.start, filters.end, filters.status) })
  const exportFin = useMutation({ mutationFn: () => exportFinancial(filters.start, filters.end) })
  const hasError = operations.isError || financial.isError || audit.isError || exportOps.isError || exportFin.isError
  return <section className="space-y-6">
    <div><h1 className="text-2xl font-bold">Relatórios</h1><p className="text-slate-600">Indicadores filtrados e exportações sem dados pessoais.</p></div>
    <form className="card grid items-end gap-3 sm:grid-cols-2 lg:grid-cols-[auto_auto_1fr_auto]" onSubmit={(event) => { event.preventDefault(); setFilters({ start, end, status }) }}><label className="min-w-0 text-sm">De<input className="input mt-1" type="date" required value={start} onChange={(event) => setStart(event.target.value)} /></label><label className="min-w-0 text-sm">Até<input className="input mt-1" type="date" required value={end} onChange={(event) => setEnd(event.target.value)} /></label><label className="min-w-0 text-sm">Status<select className="input mt-1" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos</option>{Object.entries(statusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><button className="btn-primary w-full">Aplicar filtros</button></form>
    {hasError && <div className="card text-red-700" role="alert">Não foi possível concluir uma das consultas ou exportações.</div>}
    <section className="card space-y-3" aria-labelledby="operational-report"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 id="operational-report" className="text-lg font-semibold">Relatório operacional</h2><p className="text-sm text-slate-500">Não inclui nome, CPF, CNH, telefone ou e-mail.</p></div><button type="button" className="btn-secondary" disabled={exportOps.isPending} onClick={() => exportOps.mutate()}>Exportar CSV</button></div>{operations.isLoading && <p role="status">Carregando operações…</p>}{operations.data?.data.length === 0 && <p className="text-slate-500">Nenhuma operação encontrada no período.</p>}{operations.data && operations.data.data.length > 0 && <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b"><th className="p-2">Locação</th><th className="p-2">Carreta</th><th className="p-2">Status</th><th className="p-2">Retirada</th><th className="p-2">Devolução</th><th className="p-2 text-right">Total</th></tr></thead><tbody>{operations.data.data.map((row) => <tr className="border-b border-slate-100" key={row.id}><td className="p-2 font-medium">{row.code}</td><td className="p-2">{row.trailer_code}</td><td className="p-2">{statusLabels[row.status]}</td><td className="p-2">{new Date(row.start_at).toLocaleDateString('pt-BR')}</td><td className="p-2">{new Date(row.expected_return_at).toLocaleDateString('pt-BR')}</td><td className="p-2 text-right">R$ {row.total}</td></tr>)}</tbody></table></div>}</section>
    {canViewFinancial && <section className="card space-y-3" aria-labelledby="financial-report"><div className="flex flex-wrap items-center justify-between gap-2"><h2 id="financial-report" className="text-lg font-semibold">Relatório financeiro</h2><button type="button" className="btn-secondary" disabled={exportFin.isPending} onClick={() => exportFin.mutate()}>Exportar CSV</button></div>{financial.isLoading && <p role="status">Carregando financeiro…</p>}{financial.data && <><div className="grid gap-3 sm:grid-cols-3"><div><p className="text-xs text-slate-500">Cobrado</p><strong>R$ {financial.data.charged_total}</strong></div><div><p className="text-xs text-slate-500">Pago</p><strong>R$ {financial.data.paid_total}</strong></div><div><p className="text-xs text-slate-500">Saldo</p><strong>R$ {financial.data.balance_total}</strong></div></div>{financial.data.data.length === 0 ? <p className="text-slate-500">Nenhum valor no período.</p> : <div className="grid gap-2">{financial.data.data.map((row) => <div className="grid gap-1 rounded-lg bg-slate-50 p-3 text-sm sm:grid-cols-4" key={row.rental_id}><strong>{row.rental_code}</strong><span>Cobrado: R$ {row.charged}</span><span>Pago: R$ {row.paid}</span><span>Saldo: R$ {row.balance}</span></div>)}</div>}</>}</section>}
    {canViewFinancial && <section className="card space-y-3" aria-labelledby="audit-report"><h2 id="audit-report" className="text-lg font-semibold">Auditoria</h2>{audit.isLoading && <p role="status">Carregando auditoria…</p>}{audit.data?.data.length === 0 && <p className="text-slate-500">Nenhum evento auditável no período.</p>}<div className="grid gap-2">{audit.data?.data.map((row) => <div className="flex flex-wrap justify-between gap-2 rounded-lg border border-slate-100 p-3 text-sm" key={row.id}><span><strong>{row.action}</strong> · {row.entity_type}</span><span>{new Date(row.created_at).toLocaleString('pt-BR')}</span></div>)}</div></section>}
  </section>
}
